object Dependencies {
  val akkaVersion               = "2.6.17"
  val akkaHttpVersion           = "10.2.6"
  val circeParserVersion        = "0.14.1"
  val enumeratumVersion         = "1.7.0"
  val logbackVersion            = "1.2.7"
  val mssqlConnectorJavaVersion = "8.0.25"
  val postgresqlVersion         = "42.3.1"
  val sangriaAkkaHttpVersion    = "0.0.2"
  val sangriaCirceVersion       = "1.3.2"
  val sangriaGraphqlVersion     = "2.1.5"
  val scalaLoggingVersion       = "3.9.4"
  val scalaTestVersion          = "3.2.9"
  val scalaTestMockitoVersion   = "3.2.10.0"
  val typesafeConfigVersion     = "1.4.1"
}
